plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = "com.college.cs4048_group_007"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.college.cs4048_group_007"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {

    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.activity)
    implementation(libs.constraintlayout)
    testImplementation(libs.junit)
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
}

// Configure Javadoc generation task
tasks.register<Javadoc>("generateJavadoc") {
    // Source directories for your Java/Kotlin code
    source = fileTree(android.sourceSets["main"].java.srcDirs)

    // Include the necessary classpath (Android SDK boot classpath)
    classpath = project.files(android.bootClasspath.joinToString(File.pathSeparator))

    // Configure Javadoc options
    options {
        version = true
        header = "Generated by Android Studio"
    }
}